### ISSUE TITLE
KeyError at /admin/salon/servant/4/   'request'

### ISSUE THREAD

**Issue by draculaw** [BertrandBordage/django-super-inlines#6]
Request Method: GET
Request URL:    http://192.168.56.102:8080/admin/salon/servant/4/
Django Version: 1.7.7
Exception Type: KeyError
Exception Value:  
'request'
Exception Location: /usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/context.py in **getitem**, line 70
Python Executable:  /usr/bin/python3
Python Version: 3.4.0
Python Path:  
['/home/dev/workplace/xjc',
 '/usr/local/lib/python3.4/dist-packages/mysqlclient-1.3.6-py3.4-linux-x86_64.egg',
 '/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/djangorestframework-3.1.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/Pillow-2.8.1-py3.4-linux-x86_64.egg',
 '/usr/local/lib/python3.4/dist-packages/pingpp-2.0.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/requests-2.6.0-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/alipay-0.4.2-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/six-1.9.0-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/django_alipay-0.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pep8-1.6.2-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/uWSGI-2.0.10-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/setuptools-15.0-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pip-6.1.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/Scrapy-0.24.5-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/cssselect-0.9.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pyOpenSSL-0.15.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pytz-2015.2-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pycrypto-2.6.1-py3.4-linux-x86_64.egg',
 '/usr/local/lib/python3.4/dist-packages/django_super_inlines-0.1.4-py3.4.egg',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
Server time:    Mon, 15 Jun 2015 09:44:35 +0800
Error during template rendering

In template /usr/local/lib/python3.4/dist-packages/django_super_inlines-0.1.4-py3.4.egg/super_inlines/templates/admin/edit_inline/stacked.html, error at line 56
request
46                {{ inline_admin_form.form.non_field_errors }}
47              {% endif %}
48              {% for fieldset in inline_admin_form %}
49                {% include "admin/includes/fieldset.html" %}
50              {% endfor %}
51              {% if inline_admin_form.needs_explicit_pk_field %}
52                {{ inline_admin_form.pk_field.field }}
53              {% endif %}
54              {{ inline_admin_form.fk_field.field }}
55  
56              {% get_sub_inline_formsets inline original forloop.counter0 forloop.last as sub_inlines %}
57              {% for sub_inline in sub_inlines %}
58                {% include sub_inline.opts.template with inline_admin_formset=sub_inline is_subinline=True %}
59              {% endfor %}
60  
61            </div>
62          {% endwith %}
63        {% endfor %}
64      </div>
65  
66      {% if not is_subinline %}
Traceback Switch to copy-and-paste view

/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/core/handlers/base.py in get_response
                response = response.render() ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/response.py in render
            self.content = self.rendered_content ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/response.py in rendered_content
        content = template.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
            return self._render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/loader_tags.py in render
        return compiled_parent._render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/loader_tags.py in render
        return compiled_parent._render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/loader_tags.py in render
                result = block.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/loader_tags.py in render
                result = block.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/defaulttags.py in render
                            nodelist.append(node.render(context)) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/loader_tags.py in render
                return template.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
            return self._render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/defaulttags.py in render
            return self.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/defaulttags.py in render
                return nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/defaulttags.py in render
                            nodelist.append(node.render(context)) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/defaulttags.py in render
            return self.nodelist.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/base.py in render
                    context[self.target_var] = func(_resolved_args, *_resolved_kwargs) ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/django_super_inlines-0.1.4-py3.4.egg/super_inlines/templatetags/super_inlines.py in get_sub_inline_formsets
    request = context['request'] ...
▶ Local vars
/usr/local/lib/python3.4/dist-packages/Django-1.7.7-py3.4.egg/django/template/context.py in __getitem__
        raise KeyError(key) ...
▶ Local vars
Request information

GET
No GET data
POST
No POST data
FILES
No FILES data
COOKIES
Variable    Value
csrftoken  
'RqEvKHSawakU1XxcLW8kgRD3ayPdxFox'
sessionid  
'qato16cbybwuyx2g1nn6k7oxb419juay'
META
Variable    Value
SCRIPT_NAME 
''
SERVER_PROTOCOL 
'HTTP/1.1'
TERM  
'xterm'
SSH_TTY 
'/dev/pts/3'
PATH_INFO  
'/admin/salon/servant/4/'
_  
'/usr/bin/python3'
SHELL  
'/bin/bash'
CSRF_COOKIE_USED  
True
HOME  
'/home/dev'
wsgi.run_once  
False
wsgi.input  
<_io.BufferedReader name=8>
TZ  
'Asia/Chongqing'
HTTP_COOKIE 
'sessionid=qato16cbybwuyx2g1nn6k7oxb419juay; '
'csrftoken=RqEvKHSawakU1XxcLW8kgRD3ayPdxFox'
wsgi.file_wrapper  
''
CSRF_COOKIE 
'RqEvKHSawakU1XxcLW8kgRD3ayPdxFox'
PATH  
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
XDG_SESSION_ID  
'3'
SERVER_SOFTWARE 
'WSGIServer/0.2'
HTTP_REFERER  
'http://192.168.56.102:8080/admin/salon/servant/'
QUERY_STRING  
''
LANG  
'en_US.UTF-8'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8'
LESSCLOSE  
'/usr/bin/lesspipe %s %s'
SSH_CONNECTION  
'10.61.11.73 61687 10.61.11.45 22'
MAIL  
'/var/mail/dev'
GATEWAY_INTERFACE  
'CGI/1.1'
LS_COLORS  
'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:'
SSH_CLIENT  
'10.61.11.73 61687 22'
CONTENT_TYPE  
'text/plain'
HTTP_ACCEPT_LANGUAGE  
'zh-CN,zh;q=0.8'
DJANGO_SETTINGS_MODULE  
'xjc.settings'
wsgi.version  
(1, 0)
HTTP_USER_AGENT 
'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) '
'Chrome/42.0.2311.90 Safari/537.36'
REQUEST_METHOD  
'GET'
HTTP_HOST  
'192.168.56.102:8080'
wsgi.url_scheme 
'http'
SERVER_NAME 
'dev'
HTTP_CONNECTION 
'keep-alive'
RUN_MAIN  
'true'
XDG_RUNTIME_DIR 
'/run/user/1000'
wsgi.errors 
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
wsgi.multithread  
True
PWD 
'/home/dev/workplace/xjc'
wsgi.multiprocess  
False
LESSOPEN  
'| /usr/bin/lesspipe %s'
SHLVL  
'1'
REMOTE_ADDR 
'192.168.56.1'
HTTP_ACCEPT_ENCODING  
'gzip, deflate, sdch'
SERVER_PORT 
'8080'
USER  
'dev'
LOGNAME 
'dev'
OLDPWD  
'/home/dev'
CONTENT_LENGTH  
''
REMOTE_HOST 
''
Settings
Using settings module xjc.settings
Setting Value
ROOT_URLCONF  
'xjc.urls'
LANGUAGES_BIDI  
('he', 'ar', 'fa', 'ur')
COMMENTS_ALLOW_PROFANITIES  
False
ALLOWED_HOSTS  
[]
CSRF_FAILURE_VIEW  
'django.views.csrf.csrf_failure'
SESSION_SAVE_EVERY_REQUEST  
False
DEFAULT_TABLESPACE  
''
CSRF_COOKIE_SECURE  
False
TEMPLATE_CONTEXT_PROCESSORS 
('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages')
DEBUG  
True
MANAGERS  
()
TEMPLATE_DEBUG  
True
STATICFILES_DIRS  
('/home/dev/workplace/xjc/static1/',)
DEFAULT_FROM_EMAIL  
'webmaster@localhost'
FIRST_DAY_OF_WEEK  
0
CSRF_COOKIE_DOMAIN  
None
PREPEND_WWW 
False
INTERNAL_IPS  
()
DATABASE_ROUTERS  
[]
DATABASES  
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.mysql',
             'HOST': 'localhost',
             'NAME': 'xjc',
             'OPTIONS': {},
             'PASSWORD': '*******************_',
             'PORT': '3306',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': 'xjc'}}
SQLITE_DB  
{'default': {'ENGINE': 'django.db.backends.sqlite3',
             'NAME': '/home/dev/workplace/xjc/db.sqlite3'}}
FILE_CHARSET  
'utf-8'
CACHE_MIDDLEWARE_ALIAS  
'default'
THOUSAND_SEPARATOR  
','
SESSION_EXPIRE_AT_BROWSER_CLOSE 
False
TIME_INPUT_FORMATS  
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
SESSION_FILE_PATH  
None
LOGGING_CONFIG  
'logging.config.dictConfig'
EMAIL_BACKEND  
'django.core.mail.backends.smtp.EmailBackend'
FORCE_SCRIPT_NAME  
None
MONTH_DAY_FORMAT  
'F j'
STATIC_URL  
'/static/'
SEND_BROKEN_LINK_EMAILS 
False
ABSOLUTE_URL_OVERRIDES  
{}
LOGGING 
{}
LANGUAGE_COOKIE_AGE 
None
DECIMAL_SEPARATOR  
'.'
SERVER_EMAIL  
'root@localhost'
ADMINS  
()
FORMAT_MODULE_PATH  
None
NUMBER_GROUPING 
0
SILENCED_SYSTEM_CHECKS  
[]
LANGUAGES  
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese'),
 ('zh-tw', 'Traditional Chinese'))
SHORT_DATE_FORMAT  
'm/d/Y'
WSGI_APPLICATION  
'xjc.wsgi.application'
TIME_FORMAT 
'P'
MEDIA_URL  
''
SESSION_COOKIE_HTTPONLY 
True
FILE_UPLOAD_MAX_MEMORY_SIZE 
2621440
SECRET_KEY  
'**_****************_'
USE_ETAGS  
False
BASE_DIR  
'/home/dev/workplace/xjc'
SESSION_COOKIE_DOMAIN  
None
LOGIN_URL  
'/accounts/login/'
MEDIA_ROOT  
''
TEMPLATE_STRING_IF_INVALID  
''
ADMIN_FOR  
()
DEFAULT_CONTENT_TYPE  
'text/html'
IGNORABLE_404_URLS  
()
USE_L10N  
True
LANGUAGE_COOKIE_DOMAIN  
None
DEFAULT_INDEX_TABLESPACE  
''
CACHES  
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
TIME_ZONE  
'Asia/Chongqing'
SESSION_COOKIE_NAME 
'sessionid'
FILE_UPLOAD_DIRECTORY_PERMISSIONS  
None
SESSION_SERIALIZER  
'django.contrib.sessions.serializers.JSONSerializer'
REST_FRAMEWORK  
{'PAGE_SIZE': 10}
TEMPLATE_DIRS  
()
FILE_UPLOAD_HANDLERS  
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
EMAIL_HOST  
'localhost'
SESSION_COOKIE_AGE  
1209600
CSRF_COOKIE_NAME  
'csrftoken'
SESSION_COOKIE_SECURE  
False
DATETIME_FORMAT 
'N j, Y, P'
PASSWORD_HASHERS  
'**_****************_'
TEST_NON_SERIALIZED_APPS  
[]
SESSION_ENGINE  
'django.contrib.sessions.backends.db'
PROFANITIES_LIST  
'**_****************_'
LOCALE_PATHS  
()
TEST_RUNNER 
'django.test.runner.DiscoverRunner'
YEAR_MONTH_FORMAT  
'F Y'
FILE_UPLOAD_TEMP_DIR  
None
ALLOWED_INCLUDE_ROOTS  
()
LOGIN_REDIRECT_URL  
'/accounts/profile/'
USE_THOUSAND_SEPARATOR  
False
PASSWORD_RESET_TIMEOUT_DAYS 
'**_****************_'
SETTINGS_MODULE 
'xjc.settings'
X_FRAME_OPTIONS 
'SAMEORIGIN'
MESSAGE_STORAGE 
'django.contrib.messages.storage.fallback.FallbackStorage'
TRANSACTIONS_MANAGED  
False
AUTH_USER_MODEL 
'auth.User'
CSRF_COOKIE_PATH  
'/'
DISALLOWED_USER_AGENTS  
()
FIXTURE_DIRS  
()
SIGNING_BACKEND 
'django.core.signing.TimestampSigner'
DATE_FORMAT 
'N j, Y'
EMAIL_SUBJECT_PREFIX  
'[Django] '
USE_TZ  
True
USE_X_FORWARDED_HOST  
False
STATIC_ROOT 
'/home/dev/workplace/xjc/static/'
INSTALLED_APPS  
('super_inlines',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'salon',
 'rest_framework')
LANGUAGE_COOKIE_NAME  
'django_language'
SESSION_COOKIE_PATH 
'/'
TEMPLATE_LOADERS  
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
AUTHENTICATION_BACKENDS 
('django.contrib.auth.backends.ModelBackend',)
CACHE_MIDDLEWARE_SECONDS  
600
STATICFILES_FINDERS 
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
LOGOUT_URL  
'/accounts/logout/'
CSRF_COOKIE_HTTPONLY  
False
APPEND_SLASH  
True
USE_I18N  
True
SESSION_CACHE_ALIAS 
'default'
DEFAULT_FILE_STORAGE  
'django.core.files.storage.FileSystemStorage'
EMAIL_USE_SSL  
False
DEFAULT_EXCEPTION_REPORTER_FILTER  
'django.views.debug.SafeExceptionReporterFilter'
MIGRATION_MODULES  
{}
MYSQL_DB  
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.mysql',
             'HOST': 'localhost',
             'NAME': 'xjc',
             'OPTIONS': {},
             'PASSWORD': '**_****************_',
             'PORT': '3306',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': 'xjc'}}
STATICFILES_STORAGE 
'django.contrib.staticfiles.storage.StaticFilesStorage'
EMAIL_USE_TLS  
False
CSRF_COOKIE_AGE 
31449600
DEFAULT_CHARSET 
'utf-8'
SHORT_DATETIME_FORMAT  
'm/d/Y P'
CACHE_MIDDLEWARE_KEY_PREFIX 
'**_****************_'
DEBUG_PROPAGATE_EXCEPTIONS  
False
MIDDLEWARE_CLASSES  
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')
DATE_INPUT_FORMATS  
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
FILE_UPLOAD_PERMISSIONS 
None
EMAIL_HOST_PASSWORD 
'**_*****************'
LANGUAGE_COOKIE_PATH  
'/'
DATETIME_INPUT_FORMATS  
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER 
''
SECURE_PROXY_SSL_HEADER 
None
EMAIL_PORT  
25
LANGUAGE_CODE  
'en-us'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by BertrandBordage** [comment]
Please make a proper issue. I’m not a trashcan where you can just dump entire logs.
And search a bit by yourself before reporting an error, the error you met is a basic configuration issue.

**Comment by vitorcunha1995** [comment]
I had the same error. What is the basic configuration issue you are saying @BertrandBordage ?
