### ISSUE TITLE
javascript error when adding inline

### ISSUE THREAD

**Issue by gehilley** [BertrandBordage/django-super-inlines#7]
Hi,

Thanks for the nice super-inlines package.  I am excited to use it.  After install and following the instructions, the 

$("#{{ formset.prefix }}-group").formset(onAfterAdd, postInit);

line appears to be causing a javascript error.  

Uncaught TypeError: $(...).formset is not a function

This could be due to my lack of knowledge of using Javascript – any help you might lend would be greatly appreciated.

Thanks,
george.

Running Python 3.4.3
Django 1.8.2

**Comment by BertrandBordage** [comment]
Did you put `'super_inlines'` before `'django.contrib.admin'` and `'grappelli'` in `INSTALLED_APPS`?

If so, could you clear your browser cache using ctrl+F5 (on most OS except MacOS)?

**Comment by gehilley** [comment]
Hi Bertrand,

Thanks for your suggestion.  After some additional tinkering, it seems as though there was a problem with the static file collection.  Once clearing this out and re-collecting, super-inlines seems to be working super.  Nice job, and sorry for the brief hassle.

best,
george.
